### STAGES ###
stages:
  - build
  - pull
  - test
  # - review
  # - deploy

### GLOBAL VARS ###
variables:
  BUILD_IMAGE_VERSION: latest
  IMAGE_NAME: gcr.io/krossr/client
  DOCKER_DRIVER: overlay2

### BUILD STAGE
build:
  stage: build
  image: google/cloud-sdk
  except:
    - chat
    - trigger
  script:
    - echo $GCP_SERVICE_KEY > keyfile.json
    - gcloud auth activate-service-account krossr-client@krossr.iam.gserviceaccount.com --key-file=keyfile.json
    - gcloud config set project $GCP_PROJECT_ID
    - bash ./ci/build

### TEST STAGE ###
pull image:
  stage: pull
  image: google/cloud-sdk
  artifacts:
    untracked: true
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - echo $GCP_SERVICE_KEY > keyfile.json
    - gcloud auth activate-service-account krossr-client@krossr.iam.gserviceaccount.com --key-file=keyfile.json
    - gcloud auth configure-docker
    - bash ./ci/pull_test_image 

run test:
  stage: test
  image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
  dependencies:
    - pull image
  script:
    - npm run test

# node lint:
#   cache: {}
#   stage: test
#   image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
#   script:
#     - npm run lint
