### STAGES ###
stages:
  # - build
  - test
  # - review
  # - deploy

### GLOBAL VARS ###
variables:
  BUILD_IMAGE_VERSION: latest
  IMAGE_NAME: gcr.io/krossr/client
  TAG_LOGIC: '(if [ "$${CI_COMMIT_BRANCH}" == "master" ]; then echo "latest"; else echo "$${CI_COMMIT_BRANCH}"; fi);'
  DOCKER_DRIVER: overlay2

### BUILD STAGE
# build:
#   stage: build
#   image: google/cloud-sdk
#   except:
#     - chat
#     - trigger
#   script:
#     - TAG=$(eval $TAG_LOGIC)
#     - echo $GCP_SERVICE_KEY > keyfile.json
#     - gcloud auth activate-service-account krossr-client@krossr.iam.gserviceaccount.com --key-file=keyfile.json
#     - gcloud config set project $GCP_PROJECT_ID
#     - gcloud builds submit . --config=cloudbuild.yaml --substitutions=TAG_NAME=$TAG

### TEST STAGE ###
test image:
  stage: test
  image: google/cloud-sdk
  artifacts:
    untracked: true
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - TAG=$(eval $TAG_LOGIC)
    - echo $GCP_SERVICE_KEY > keyfile.json
    - gcloud auth activate-service-account krossr-client@krossr.iam.gserviceaccount.com --key-file=keyfile.json
    - gcloud auth configure-docker
    - docker run -d --name $TAG gcr.io/krossr/client:${TAG}
    - docker exec $TAG npm run test
    - docker stop $TAG 

# node lint:
#   cache: {}
#   stage: test
#   image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
#   script:
#     - npm run lint
