### STAGES ###
stages:
  - build
  # - test
  # - review
  # - deploy

### GLOBAL VARS ###
variables:
  BUILD_IMAGE_VERSION: latest
  IMAGE_NAME: gcr.io/krossr/client
  DOCKER_DRIVER: overlay2

### BUILD STAGE
build:
  stage: build
  image: google/cloud-sdk
  except:
    - chat
    - trigger
  script:
    - echo $GCP_SERVICE_KEY > keyfile.json
    - gcloud auth activate-service-account krossr-client@krossr.iam.gserviceaccount.com --key-file=keyfile.json
    - gcloud config set project $GCP_PROJECT_ID
    - /bin/sh ./ci/set-tag
    - echo $TAG
    # - gcloud builds submit . --config=cloudbuild.yaml --substitutions=_TAG=${TAG}

### TEST STAGE ###
# karma:
#   stage: test
#   image: google/cloud-sdk
#   services:
#     - docker:dind
#   script:
#     - ./ci/set-tag
#     - echo $TAG

# node lint:
#   cache: {}
#   stage: test
#   image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
#   script:
#     - npm run lint
