### STAGES ###
stages:
  - install_dependencies
  # - build
  - test
  # - review
  # - deploy

### DEPENDENCIES
install_dependencies:
    stage: install_dependencies
    cache:
        key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
        paths:
          - node_modules/
    script:
      - npm install
    only:
      changes:
        - package-lock.json

### GLOBAL VARS ###
variables:
  BUILD_IMAGE_VERSION: latest
  IMAGE_NAME: registry.gitlab.com/${CI_PROJECT_PATH}
  DOCKER_DRIVER: overlay2

### TEST STAGE ###
node test:
  stage: test
  image: zenika/alpine-chrome:with-node
  script:
    - npm run test

node lint:
  stage: test
  image: registry.gitlab.com/picrossr/images/build-image:${BUILD_IMAGE_VERSION}
  script:
    - npm run lint
