steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    id: "docker-build"
    args:
      - --destination=gcr.io/krossr/client:${TAG_NAME}
      - --cache=true
      - --build-arg=NODE_ENV=production
timeout: 900s